version: 2

models:
  - name: concat_indeed_linkedin
    description: concatenation of cleaned data from linkedin and indeed
    columns:

    - name: info_source
      description: source of the ad, linkedin or indeed
      tests:
        - not_null

    - name: job_title
      description: simplified job title from the job ad
      tests:
        - not_null

    - name: job_title_category
      description: categorisation of the job title to separate data analyst, business analyst, BI specialist and others jobs

    - name: company
      description: company name from the job ad
      tests:
        - not_null

    - name: posted_date
      description: posted date of the ad
      tests:
        - not_null

    - name: job_function
      description: function of the posittion, only for linkedin

    - name: salary
      description: salary range indicated in the ad

    - name: job_type
      description: type of position, only for linkedin

    - name: hierarchy
      description: position hierarchy, only for linkedin

    - name: sector
      description: company activity sector, only for linkedin

    - name: whole_desc
      description: job description
      tests:
        - not_null

    - name: contract_type
      description: contract type, defined from several columns
      tests:
        - not_null

    - name: work_type
      description: working from home inluded partially or fully in the position, defined from several columns
      tests:
        - not_null

    - name: ville
      description: city of the position

    - name: latitude
      description: latitude of the city
            
    - name: longitude
      description: longitude of the city

    - name: departement
      description: french departement of the city

    - name: region
      description: french region of the city